### ISSUE TITLE
Future evolution of the HTTP service

### ISSUE THREAD

**Issue by stevepeak** [storyscript/http#31]
One idea that came up was to migrate this gateway into a Lua package directly in Nginx. Opening this thread to discuss how that could look.

**Comment by Vesuvium** [comment]
I can say that despite the theory that says Lua it's very good, it's not: writing Lua is an excruciating experience, comparable to pre-es5 JavaScript or PHP 5.

**Comment by Vesuvium** [comment]
Form the docs there are nginx modules for embedded Clojure, Java, Javascript, PHP5 and 7. 

>> This change should significantly improve throughput.

If this is a long term solution, with constraints on throughput and stack length, I imagine the solution might be in rust, because of C interoperability and better control on performance. There are no out-of-the-box nginx modules for rust though, only some work in progress.

**Comment by FooBarWidget** [comment]
As the author of the [Passenger application server](https://www.phusionpassenger.com), I would advise against implementing this functionality as an Nginx module. Developing Nginx modules is *very* hard and error-prone. The people with the proper skills are difficult to hire.

Lua in Nginx is already easier, but the dev-reload cycle is still very bad. Worse, the Nginx lua module does not support the latest few Nginx versions, and this has been the situation for quite a while now.

If your goal is to reduce the number of moving pieces in the infrastructure (or at least, making it more manageable), then there are a number of better alternatives I believe:

- Providing a Docker base image with both Nginx and asyncy-http already baked in.
- Providing Kubernetes yaml files or Helm descriptions.
- Providing DEB/RPM packages.
- Better documentation on how to setup an Nginx reverse proxy. After all, "hard" is in the eye of the beholder. If it's just a matter of copy-pasting a few config lines in Nginx, that's a lot more acceptable nowadays than it used to be.

**Comment by stevepeak** [comment]
@FooBarWidget Thank you for this great insight and feedback. Did not fully research the nginx route, and now that seems like a fools errand. 

I'm curious what path you see as the most effective. Specifically interested in what K8S+Helm can offer as we are looking into using Helm to bootstrap the entire platform to help customers get up and running quickly.

**Comment by FooBarWidget** [comment]
The best option depends on who your customers are. What infrastructure do
they have? What is their experience level? What is their use case, etc? I
would be happy to help you with advice on that aspect. I see you are in
Amsterdam. Let's grab a coffee some time?

Op ma 28 jan. 2019 19:01 schreef Steve Peak <notifications@github.com:

**Comment by judepereira** [comment]
@FooBarWidget @stevepeak the better approach to this would be to just create Kubernetes Ingress rules and trash this component altogether. This way, all endpoints would hit the engine directly.
